apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajv
  template:
    metadata:
      labels:
        app: ajv
    spec:
      containers:
        - name: ajv-container
          image: rishithamarri/ajv-docker:docker-aa04cf1f433449a1eb51139c030bc04732caf04a
          ports:
            - containerPort: 80
