apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajv
  template:
    metadata:
      labels:
        app: ajv
    spec:
      containers:
        - name: ajv-container
          image: rishithamarri/ajv-docker:docker-69a015b6502496f2ec47b476dbf705d3c3fdc168
          ports:
            - containerPort: 80
