apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajv
  template:
    metadata:
      labels:
        app: ajv
    spec:
      containers:
        - name: ajv-container
          image: $REPO_NAME/$IMAGE_NAME:docker-64c237641cadeff2b602a9e9c1ef467323c70afa
          ports:
            - containerPort: 80
