apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ajv
  template:
    metadata:
      labels:
        app: ajv
    spec:
      containers:
        - name: ajv-container
          image: $REPO_NAME/$IMAGE_NAME:docker-fbf9ace0bd0bac5100b8182e03420dc76594b5b7
          ports:
            - containerPort: 80
